apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  volumes:
  - name: kuard-data
    persistentVolumeClaim:
      claimName: kuard-data
  - name: config-volume
    configMap:
      name: my-config
  - name: tls-certs
    secret:
      secretName: kuard-tls
  #imagePullSecrets: # This is a list of secrets that can be used to pull images from private registries
  #  - name:  kube-registry-secret # This is the name of the secret
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:1
      name: kuard
      imagePullPolicy: Always
      env:
        - name: ANOTHER_PARAM
          valueFrom:
            configMapKeyRef:
              name: my-config 
              key: another-param
        - name: EXTRA_PARAM
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: extra-param
      resources:
        requests:
          cpu: 500m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 128Mi
      volumeMounts:
        - name: kuard-data
          mountPath: /data
        - name: config-volume
          mountPath: /config
          readOnly: true
        - name: tls-certs
          mountPath: /tls
          readOnly: true
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP