apiVersion: v1
kind: Service
metadata: # The metadata for the service
  name: kuard
spec:
  type: NodePort
  selector: # Selects the pods that are part of the Service
    app: kuard
  ports:
    - port: 80 # The port that this service should serve on.
      targetPort: 8080 # This is the port that the container listens on
      nodePort: 30080 # This is the port that the service will be exposed on