apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot-job
  labels:
    chapter: jobs
    component: oneshot
    app: worker-queue
spec:
  parallelism: 5
  template:
    metadata:
      name: oneshot-job
      labels:
        chapter: jobs
        component: oneshot
        app: worker-queue
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        imagePullPolicy: Always
        args:
          - "--keygen-enable"
          - "--keygen-exit-on-complete"
          - "--keygen-memq-server=http://queue:8000/memq/server"
          - "--keygen-memq-queue=keygen"
      restartPolicy: OnFailure