apiVersion: v1
kind: Service
metadata:
  name: queue
  labels:
    app: worker-queue
    component: queue
    chapter: jobs
spec:
  type: NodePort
  selector:
    app: worker-queue
    component: queue
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
