apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  type: NodePort
  selector:
    app: mysql-rs
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30006
      protocol: TCP